spring:
  ## MYSQL ##
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

## serverName ##
server:
  url: localhost
  ## https
  tomcat:
    use-relative-redirects: true

  ## timeout ??
  servlet:
    session:
      timeout: 1800